# Generated by Django 5.0.7 on 2024-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_remove_product_stock_alter_tedad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد باقی مانده'),
        ),
    ]
