# Generated by Django 5.0.7 on 2024-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_remove_customer_user_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeOrder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان سفارش'),
        ),
    ]
